version: '3'
services:
  db_chip_coffee:
    build:
      context: ./
      dockerfile: MySQL.Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD : 'yes'
    restart: always
  db_admin_ChipCoffee:
    image: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
    volumes:
     - /sessions